v1.7.7

diff --git a/tron b/tron
--- a/tron
+++ b/tron
@@ -231,7 +231,7 @@ function banner(){
 
 
 
-.6
+.7
 
 $endc"""
 sleep 0.05
@@ -241,7 +241,7 @@ clear
 
 
 
-.7.6
+.7.7
 
 $endc"""
 sleep 0.05
@@ -251,7 +251,7 @@ clear
  / /
 / /
  /
-/ v1.7.6
+/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -261,7 +261,7 @@ __   __
   | / /
   |/ /
 /|  /
- |_/ v1.7.6
+ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -271,7 +271,7 @@ ______   __
  \__  | / /
  /_   |/ /
 /_  /|  /
- /_/ |_/ v1.7.6
+ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -281,7 +281,7 @@ ________   __
 __ \__  | / /
  / /_   |/ /
 / /_  /|  /
-_/ /_/ |_/ v1.7.6
+_/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -291,7 +291,7 @@ __________   __
   __ \__  | / /
  / / /_   |/ /
 /_/ /_  /|  /
-___/ /_/ |_/ v1.7.6
+___/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -303,7 +303,7 @@ ____________   __
 \_  __ \__  | / /
 /  / / /_   |/ /
 / /_/ /_  /|  /
-\____/ /_/ |_/ v1.7.6
+\____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -314,7 +314,7 @@ ______________   __
 _ \_  __ \__  | / /
 / /  / / /_   |/ /
 _// /_/ /_  /|  /
-| \____/ /_/ |_/ v1.7.6
+| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -325,7 +325,7 @@ ________________   __
  __ \_  __ \__  | / /
 /_/ /  / / /_   |/ /
 , _// /_/ /_  /|  /
-|_| \____/ /_/ |_/ v1.7.6
+|_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -336,7 +336,7 @@ ___________________   __
 __  __ \_  __ \__  | / /
 _  /_/ /  / / /_   |/ /
   _, _// /_/ /_  /|  /
-_/ |_| \____/ /_/ |_/ v1.7.6
+_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -348,7 +348,7 @@ ______________________   __
 __/__  __ \_  __ \__  | / /
   __  /_/ /  / / /_   |/ /
   _  _, _// /_/ /_  /|  /
-  /_/ |_| \____/ /_/ |_/ v1.7.6
+  /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -359,7 +359,7 @@ ________________________   __
   __/__  __ \_  __ \__  | / /
  /  __  /_/ /  / / /_   |/ /
 /   _  _, _// /_/ /_  /|  /
-    /_/ |_| \____/ /_/ |_/ v1.7.6
+    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -370,7 +370,7 @@ __________________________   __
 __  __/__  __ \_  __ \__  | / /
 _  /  __  /_/ /  / / /_   |/ /
   /   _  _, _// /_/ /_  /|  /
-_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -382,7 +382,7 @@ ____________________________   __
 ____  __/__  __ \_  __ \__  | / /
 ___  /  __  /_/ /  / / /_   |/ /
 __  /   _  _, _// /_/ /_  /|  /
-_/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -393,7 +393,7 @@ ______________________________   __
 ______  __/__  __ \_  __ \__  | / /
 _____  /  __  /_/ /  / / /_   |/ /
 ____  /   _  _, _// /_/ /_  /|  /
-___/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+___/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -404,7 +404,7 @@ ________________________________   __
 ________  __/__  __ \_  __ \__  | / /
 _______  /  __  /_/ /  / / /_   |/ /
 ______  /   _  _, _// /_/ /_  /|  /
-_____/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_____/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -416,7 +416,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 
@@ -431,7 +431,7 @@ function pride_banner(){
 
 
 
-.6
+.7
 
 $endc"""
 sleep 0.05
@@ -441,7 +441,7 @@ clear
 
 
 
-.7.6
+.7.7
 
 $endc"""
 sleep 0.05
@@ -451,7 +451,7 @@ clear
  / /
 / /
  /
-/ v1.7.6
+/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -461,7 +461,7 @@ __   __
   | / /
   |/ /
 /|  /
- |_/ v1.7.6
+ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -471,7 +471,7 @@ ______   __
  \__  | / /
  /_   |/ /
 /_  /|  /
- /_/ |_/ v1.7.6
+ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -481,7 +481,7 @@ ________   __
 __ \__  | / /
  / /_   |/ /
 / /_  /|  /
-_/ /_/ |_/ v1.7.6
+_/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -491,7 +491,7 @@ __________   __
   __ \__  | / /
  / / /_   |/ /
 /_/ /_  /|  /
-___/ /_/ |_/ v1.7.6
+___/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -503,7 +503,7 @@ ____________   __
 \_  __ \__  | / /
 /  / / /_   |/ /
 / /_/ /_  /|  /
-\____/ /_/ |_/ v1.7.6
+\____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -514,7 +514,7 @@ ______________   __
 _ \_  __ \__  | / /
 / /  / / /_   |/ /
 _// /_/ /_  /|  /
-| \____/ /_/ |_/ v1.7.6
+| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -525,7 +525,7 @@ ________________   __
  __ \_  __ \__  | / /
 /_/ /  / / /_   |/ /
 , _// /_/ /_  /|  /
-|_| \____/ /_/ |_/ v1.7.6
+|_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -536,7 +536,7 @@ ___________________   __
 __  __ \_  __ \__  | / /
 _  /_/ /  / / /_   |/ /
   _, _// /_/ /_  /|  /
-_/ |_| \____/ /_/ |_/ v1.7.6
+_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -548,7 +548,7 @@ ______________________   __
 __/__  __ \_  __ \__  | / /
   __  /_/ /  / / /_   |/ /
   _  _, _// /_/ /_  /|  /
-  /_/ |_| \____/ /_/ |_/ v1.7.6
+  /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -559,7 +559,7 @@ ________________________   __
   __/__  __ \_  __ \__  | / /
  /  __  /_/ /  / / /_   |/ /
 /   _  _, _// /_/ /_  /|  /
-    /_/ |_| \____/ /_/ |_/ v1.7.6
+    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -570,7 +570,7 @@ __________________________   __
 __  __/__  __ \_  __ \__  | / /
 _  /  __  /_/ /  / / /_   |/ /
   /   _  _, _// /_/ /_  /|  /
-_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -582,7 +582,7 @@ ____________________________   __
 ____  __/__  __ \_  __ \__  | / /
 ___  /  __  /_/ /  / / /_   |/ /
 __  /   _  _, _// /_/ /_  /|  /
-_/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -593,7 +593,7 @@ ______________________________   __
 ______  __/__  __ \_  __ \__  | / /
 _____  /  __  /_/ /  / / /_   |/ /
 ____  /   _  _, _// /_/ /_  /|  /
-___/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+___/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -604,7 +604,7 @@ ________________________________   __
 ________  __/__  __ \_  __ \__  | / /
 _______  /  __  /_/ /  / / /_   |/ /
 ______  /   _  _, _// /_/ /_  /|  /
-_____/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_____/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 sleep 0.05
@@ -616,7 +616,7 @@ __________________________________   __${pink}
 __________  __/__  __ \_  __ \__  | / /${green}
 _________  /  __  /_/ /  / / /_   |/ / ${red}
 ________  /   _  _, _// /_/ /_  /|  /  ${yellow}
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 
@@ -630,7 +630,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 
@@ -641,7 +641,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
                       made by Aristos with ♥
 $endc"""
 
@@ -652,7 +652,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 
@@ -663,7 +663,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
                       made by Aristos with ♥
 $endc"""
 
@@ -674,7 +674,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 
@@ -685,7 +685,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
                       made by Aristos with ♥
 $endc"""
 }
@@ -696,7 +696,7 @@ __________________________________   __
 __________  __/__  __ \_  __ \__  | / /
 _________  /  __  /_/ /  / / /_   |/ /
 ________  /   _  _, _// /_/ /_  /|  /
-_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.6
+_______/_/    /_/ |_| \____/ /_/ |_/ v1.7.7
 
 $endc"""
 }
@@ -860,9 +860,13 @@ function install_rust_default() {
     #for all users
     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 
-    # Merge existing Rust binaries into the global directory
-    ln -s ~/.cargo/bin/* /usr/bin/
-
+    if [[ $is_root == 1 ]]
+    then
+        # Merge existing Rust binaries into the global directory
+        ln -s ~/.cargo/bin/* /usr/bin/
+    else
+        ln -s ~/.cargo/bin/* ~/.local/bin/
+    fi
 }
 
 function check_dependecies() {
@@ -874,7 +878,7 @@ function check_dependecies() {
         sleep 2
         if [[ $program == "msfvenom" ]]
         then
-            if [[ $os == "Debian" || $os == "Ubuntu" || $os == "Azure" ]]
+            if [[ $os == "Debian" || $os == "Ubuntu" || $os == "Azure" || $is_root == 0 ]]
             then
                 curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
                 chmod 755 msfinstall && \
@@ -883,10 +887,8 @@ function check_dependecies() {
             else
                 apt-get install metasploit-framework -y
             fi
-        elif [[ $program == "rustup" && ( $os == "Debian" || $os == "Parrot" ) ]]
+        elif [[ $program == "rustup" && ( $os == "Debian" || $os == "Parrot" || $is_root == 0 ) ]]
         then
-            echo -e "${red}[-]${endc} $program not found in repositories. Using alternate installation method."
-            sleep 1
             echo -e "${blue}[*]${endc} Installing Rustup using official installer for $distro."
             install_rust_default
         elif [[ $program == "apache2" ]]
@@ -930,7 +932,13 @@ function check_dependecies() {
                 fi
             done
         else
-            apt-get install $program -y
+            if [[ $is_root == 1 ]]
+            then
+                apt-get install $program -y
+            else
+                echo -e "${red}[-]${endc} $program cannot be installed because the script is not running as root."
+                exit 1
+            fi
         fi
 
         echo -e "\n"
@@ -1028,15 +1036,24 @@ function checking_internet {
 }
 
 function update_system {
+    echo -e "${blue}[*]${endc} Performing Updates\n"
     apt update -y
 }
 function updates() {
     echo -e "${blue}[*]${endc} Performing Updates"
-    apt install mingw-w64 -y
+    if [[ $is_root == 0 ]]
+    then
+        clear
+        stable_banner
+        echo -e "${blue}[*]${endc} Make sure you have installed 'mingw-w64' using 'sudo apt install mingw-w64 -y'."
+        read -n 1 -s -r -p "Press any key to continue..."
+    else
+        apt install mingw-w64 -y
+    fi
     rustup update 2>/dev/null
     rustup default stable 2>/dev/null
     rustup target add x86_64-pc-windows-gnu
-    apt-get install metasploit-framework -y
+    msfupdate
     #tron_theme
     sleep 1.5
 }
@@ -1044,9 +1061,28 @@ function updates() {
 
 
 function check_root(){
+    echo -ne "${blue}[*]${endc} Checking Root privileges"
+    sleep 0.2
+    echo -n "."
+    sleep 0.2
+    echo -n "."
+    sleep 0.2
+    echo -n "."
+    sleep 0.2
+    echo "."
     if [[ $EUID -ne 0 ]]; then
-        echo -e "${red}[-] ${endc}Please run this script as root." 1>&2
-        exit 1
+        echo -e "\033[F\r\033[K${red}[-]${endc} No Root"
+        sleep 0.5
+        is_root=0
+
+        echo -e "${blue}[*]${endc} Without root privileges, updates and some installations cannot be performed."
+        echo -e "${blue}[*]${endc} However, if the required programs are already installed, the script will still work."
+        #echo -n "Press any key to continue..."
+        read -n 1 -s -r -p "Press any key to continue..."
+    else 
+        echo -e "\033[F\r\033[K${green}[+]${endc} I am Root\n"
+        sleep 0.5
+        is_root=1
     fi
 }
 
@@ -1820,9 +1856,10 @@ stable_banner
 checking_internet
 sleep 1
 
-echo -e "${blue}[*]${endc} Performing Updates\n"
-update_system
-
+if [[ $is_root == 1 ]]
+then
+    update_system
+fi
 
 clear
 stable_banner
